In [3]:
include("ha-trade-environment.jl")
include("ha-trade-solution.jl")
include("ha-trade-helper-functions.jl")

using Plots
using FiniteDifferences

In [17]:
mdl_prm = model_params(Ncntry = 5, Na = 100, Nshocks = 5, γ = 3.0, ϕ = 3, amax = 8.0, σ = 0.3919, ρ = 0.20);

@unpack Na, Nshocks, Ncntry, β = mdl_prm

gc = repeat(range(0.1,3,Na),1,Nshocks,Ncntry)

v = -ones(size(gc)) / (1- β)

country = 1

p = 1.5.*ones(Ncntry)

p[country] = 1.0

R = 1.029;
W = 1.0;

@time hh = solve_household_problem(R, W, p, mdl_prm, solution_method = "itteration");

  0.513765 seconds (66.12 k allocations: 47.121 MiB)


In [19]:
hh.πprob[1:2,1:2,1]

2×2 Matrix{Float64}:
 1.0  0.999968
 1.0  0.997707

In [15]:
typeof(foo)

Vector{Float64} (alias for Array{Float64, 1})

In [41]:
function f(x)
    
    p = 1.5.*ones(mdl_prm.Ncntry)
    
    p[1] = 1.0
    
    p[2] = x[1]
    
    solve_household_problem(R, W, p, mdl_prm, solution_method = "itteration").πprob[:,:,1]
    
end

f (generic function with 1 method)

In [42]:
f(1.5)

100×5 Matrix{Float64}:
 1.0       0.999968  0.935712  0.763639  0.63925
 1.0       0.997707  0.905405  0.750708  0.633672
 0.999988  0.986877  0.880148  0.738752  0.628305
 0.998752  0.973466  0.857864  0.727575  0.62314
 0.994791  0.949192  0.835353  0.717116  0.618155
 0.984848  0.924419  0.814268  0.707411  0.613325
 0.964942  0.896795  0.797328  0.698362  0.608652
 0.944022  0.874424  0.781935  0.689847  0.604134
 0.918588  0.852023  0.76782   0.681859  0.599762
 0.894994  0.831365  0.754807  0.674447  0.595522
 0.872483  0.813244  0.742632  0.667427  0.591405
 0.851339  0.795897  0.731229  0.660727  0.587401
 0.832084  0.78128   0.720693  0.654325  0.583506
 ⋮                                       
 0.467948  0.460725  0.448469  0.423684  0.286726
 0.465847  0.458541  0.446011  0.419772  0.277808
 0.463732  0.456333  0.443503  0.415418  0.270214
 0.461601  0.454091  0.440953  0.410695  0.263695
 0.459452  0.451808  0.438337  0.405947  0.258055
 0.457278  0.449473  0.435649  0.4008

In [44]:
jacobian(central_fdm(2, 1), f, [1.5])[1]

500×1 Matrix{Float64}:
 0.0
 5.801514306556955e-9
 8.914606883455418e-5
 0.006009237526303227
 0.01738077121479975
 0.044298065845203516
 0.0770847002859222
 0.11270468408519146
 0.13429649896319135
 0.16357550884659416
 0.175418142901326
 0.18020532044652457
 0.18585647980755562
 ⋮
 0.058280910435952925
 0.051875082842032044
 0.0464711173033319
 0.041873785611543986
 0.03793185389172495
 0.034527178656157516
 0.03156664995135716
 0.028976262210450864
 0.026696657239811097
 0.024679849264229746
 0.022886738978037773
 0.021285209923223365