In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import sys
from copy import copy

sys.path.append('../code/python')
from hat_support import *
from hat_solution import *

### Model without quality

In [2]:
# Parameters
β = 0.92        # Discount Rate
γ = 1.5         # EIS
φ = -0.5        # Borrowing Constraint
σ_ε = 0.25      # Standard deviation of logit shock
N = 2           # Number of countries

# Set up grids
n_p, n_iid, ρ_p, σ_p, σ_iid = 5, 2, 0.9, 0.039**0.5, 0.0522**0.5 
log_zgrid, P = markov_chain(n_p, n_iid, ρ_p, σ_p, σ_iid)
zgrid = np.exp(log_zgrid)
agrid = np.linspace(φ, 8, 100) 

# Country parameters
L = np.array([1, 1])
TFP = np.array([1, 1])
τ = np.array([0, 0])

d_ij = 1.745
d = np.array([[1.0, d_ij], [d_ij, 1.0]])
numeraire_cntry = N-1
ψ_slope = 0.

# Create Model Instance
m = MulticountryHATmodel(β, γ, φ, σ_ε, N, P, L, TFP, τ, d, agrid, zgrid, ψ_slope, numeraire_cntry)

# Solve for the financial globalization equilibrium 
R0 = 1.02
x0 = np.array([R0, 1.0])
eqm = m.find_equilibrium_FG(x0)

In [3]:
# Equilibrium R
eqm.R


1.0141938690670584

In [4]:
# Trade shares
eqm.tradeshares


array([[0.90048373, 0.09951627],
       [0.09951631, 0.90048369]])

In [5]:
# Probability that household 1 buys from country 2
eqm.π_i[:,:,0,1]


array([[0.00747609, 0.0192432 , 0.02024335, 0.03865408, 0.04377192,
        0.06901915, 0.07912538, 0.10381408, 0.12343206, 0.13861941],
       [0.01392841, 0.02121626, 0.0281047 , 0.04282353, 0.05181585,
        0.07116514, 0.08617555, 0.10527656, 0.12709288, 0.13928829],
       [0.01947563, 0.02643934, 0.03571973, 0.04568826, 0.05926711,
        0.07357446, 0.09175838, 0.10661265, 0.12960767, 0.13994122],
       [0.0218411 , 0.02822919, 0.0387705 , 0.04786419, 0.06361865,
        0.0757104 , 0.0957156 , 0.10780557, 0.13105274, 0.14058342],
       [0.02655126, 0.03026675, 0.04297596, 0.05067094, 0.06689129,
        0.07738895, 0.09797106, 0.10891112, 0.13226617, 0.14121594],
       [0.02850408, 0.03330283, 0.04576738, 0.05305944, 0.0701268 ,
        0.07894851, 0.10005029, 0.10996665, 0.13327754, 0.14183652],
       [0.03062496, 0.03522613, 0.04800609, 0.05482747, 0.07194198,
        0.08074442, 0.10178331, 0.11101517, 0.13425263, 0.14244926],
       [0.03339049, 0.03712232, 0.0507749

## Model with quality

In [6]:
# Parameters
β = 0.92        # Discount Rate
γ = 1.5         # EIS
φ = -0.5        # Borrowing Constraint
σ_ε = 0.25      # Standard deviation of logit shock
N = 2           # Number of countries

# Set up grids
n_p, n_iid, ρ_p, σ_p, σ_iid = 5, 2, 0.9, 0.039**0.5, 0.0522**0.5 
log_zgrid, P = markov_chain(n_p, n_iid, ρ_p, σ_p, σ_iid)
zgrid = np.exp(log_zgrid)
agrid = np.linspace(φ, 8, 100) 

# Country parameters
L = np.array([1, 1])
TFP = np.array([1, 1])
τ = np.array([0, 0])

d_ij = 1.745
d = np.array([[1.0, d_ij], [d_ij, 1.0]])
numeraire_cntry = N-1
ψ_slope = 0.2

# Create Model Instance
m_quality = MulticountryHATmodel(β, γ, φ, σ_ε, N, P, L, TFP, τ, d, agrid, zgrid, ψ_slope, numeraire_cntry)

# Solve for the financial globalization equilibrium 
R0 = 1.02
x0 = np.array([R0, 1.0])
eqm_quality = m_quality.find_equilibrium_FG(x0)

In [7]:
# Equilibrium R
eqm_quality.R


1.0130471586698062

In [8]:
# Trade shares
eqm_quality.tradeshares


array([[0.96183997, 0.03816003],
       [0.03816006, 0.96183994]])

In [9]:
# Probability that household 1 buys from country 2
eqm_quality.π_i[:,:,0,1]


array([[0.00600054, 0.01360403, 0.01429958, 0.02252287, 0.02550504,
        0.02986809, 0.0343869 , 0.02830808, 0.03412666, 0.01793637],
       [0.01115793, 0.01497122, 0.01988137, 0.02496865, 0.03028698,
        0.03090967, 0.03760708, 0.028754  , 0.03535243, 0.0180371 ],
       [0.01566571, 0.01873595, 0.02535728, 0.02670949, 0.03481642,
        0.03199442, 0.04032494, 0.02912406, 0.03624455, 0.01813621],
       [0.01753116, 0.02001485, 0.02758933, 0.02794155, 0.0375162 ,
        0.03295368, 0.04227434, 0.02947792, 0.03681643, 0.018235  ],
       [0.02143997, 0.02144417, 0.0306166 , 0.02968846, 0.03956402,
        0.03374917, 0.04345003, 0.02981345, 0.03718175, 0.01833228],
       [0.02296985, 0.02364189, 0.03268172, 0.03117147, 0.0415691 ,
        0.03446246, 0.04445798, 0.03014647, 0.03752135, 0.01842377],
       [0.02466421, 0.02504467, 0.03422594, 0.03220971, 0.04266099,
        0.03527687, 0.04530753, 0.03046113, 0.03782931, 0.01851337],
       [0.02698711, 0.02640092, 0.0363153