In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import sys
from copy import copy

sys.path.append('../code/python')
from hat_support import *
from hat_solution import *

### Model without quality

In [2]:
# Parameters
β = 0.92        # Discount Rate
γ = 1.5         # EIS
φ = -0.5        # Borrowing Constraint
σ_ε = 0.25      # Standard deviation of logit shock
N = 2           # Number of countries

# Set up grids
n_p, n_iid, ρ_p, σ_p, σ_iid = 5, 2, 0.9, 0.039**0.5, 0.0522**0.5 
log_zgrid, P = markov_chain(n_p, n_iid, ρ_p, σ_p, σ_iid)
zgrid = np.exp(log_zgrid)
agrid = np.linspace(φ, 8, 100) 

# Country parameters
L = np.array([1, 1])
TFP = np.array([1, 1])
τ = np.array([0, 0])

d_ij = 1.745
d = np.array([[1.0, d_ij], [d_ij, 1.0]])
numeraire_cntry = N-1
ψ_slope = 0.

# Create Model Instance
m = MulticountryHATmodel(β, n_p, n_iid, ρ_p, σ_p, σ_iid, γ, φ, σ_ε, N, P, L, TFP, τ, d, agrid, zgrid, ψ_slope, numeraire_cntry)

# Solve for the financial globalization equilibrium 
R0 = 1.02
x0 = np.array([R0, 1.0])
eqm = m.find_equilibrium_FG(x0)

In [3]:
# Equilibrium R
eqm.R


1.0141938690670584

In [4]:
# Trade shares
eqm.tradeshares

array([[0.90048373, 0.09951627],
       [0.09951631, 0.90048369]])

In [5]:
# Probability that household 1 buys from country 2
eqm.π_i[:,:,0,1]


array([[0.00747609, 0.0192432 , 0.02024335, 0.03865408, 0.04377192,
        0.06901915, 0.07912538, 0.10381408, 0.12343206, 0.13861941],
       [0.01392841, 0.02121626, 0.0281047 , 0.04282353, 0.05181585,
        0.07116514, 0.08617555, 0.10527656, 0.12709288, 0.13928829],
       [0.01947563, 0.02643934, 0.03571973, 0.04568826, 0.05926711,
        0.07357446, 0.09175838, 0.10661265, 0.12960767, 0.13994122],
       [0.0218411 , 0.02822919, 0.0387705 , 0.04786419, 0.06361865,
        0.0757104 , 0.0957156 , 0.10780557, 0.13105274, 0.14058342],
       [0.02655126, 0.03026675, 0.04297596, 0.05067094, 0.06689129,
        0.07738895, 0.09797106, 0.10891112, 0.13226617, 0.14121594],
       [0.02850408, 0.03330283, 0.04576738, 0.05305944, 0.0701268 ,
        0.07894851, 0.10005029, 0.10996665, 0.13327754, 0.14183652],
       [0.03062496, 0.03522613, 0.04800609, 0.05482747, 0.07194198,
        0.08074442, 0.10178331, 0.11101517, 0.13425263, 0.14244926],
       [0.03339049, 0.03712232, 0.0507749

### Model with quality

In [6]:
# Parameters
β = 0.92        # Discount Rate
γ = 1.5         # EIS
φ = -0.5        # Borrowing Constraint
σ_ε = 0.25      # Standard deviation of logit shock
N = 2           # Number of countries

# Set up grids
n_p, n_iid, ρ_p, σ_p, σ_iid = 5, 2, 0.9, 0.039**0.5, 0.0522**0.5 
log_zgrid, P = markov_chain(n_p, n_iid, ρ_p, σ_p, σ_iid)
zgrid = np.exp(log_zgrid)
agrid = np.linspace(φ, 8, 100) 

# Country parameters
L = np.array([1, 1])
TFP = np.array([1, 1])
τ = np.array([0, 0])

d_ij = 1.745
d = np.array([[1.0, d_ij], [d_ij, 1.0]])
numeraire_cntry = N-1
ψ_slope = 0.2

# Create Model Instance
m_quality = MulticountryHATmodel(β, n_p, n_iid, ρ_p, σ_p, σ_iid, γ, φ, σ_ε, N, P, L, TFP, τ, d, agrid, zgrid, ψ_slope, numeraire_cntry)

# Solve for the financial globalization equilibrium 
R0 = 1.02
x0 = np.array([R0, 1.0])
eqm_quality = m_quality.find_equilibrium_FG(x0)

In [7]:
# Equilibrium R
eqm_quality.R


1.0130750289825692

In [8]:
# Trade shares
eqm_quality.tradeshares


array([[0.91929344, 0.08070656],
       [0.08070659, 0.91929341]])

In [9]:
# Probability that household 1 buys from country 2
eqm_quality.π_i[:,:,0,1]


array([[0.01538743, 0.03897131, 0.0289009 , 0.05461008, 0.043824  ,
        0.06911751, 0.05645974, 0.07496085, 0.06400534, 0.0728029 ],
       [0.02842162, 0.042925  , 0.03995213, 0.06039286, 0.05185825,
        0.07129293, 0.06161966, 0.07606074, 0.06614226, 0.07318292],
       [0.03941862, 0.05291723, 0.05056005, 0.06433033, 0.059322  ,
        0.07370181, 0.06582656, 0.0770306 , 0.06765543, 0.07355681],
       [0.04411935, 0.05650297, 0.0547915 , 0.067391  , 0.06370104,
        0.07582942, 0.06882718, 0.07791609, 0.0685637 , 0.07392414],
       [0.05313115, 0.0605085 , 0.0605846 , 0.07117284, 0.06697975,
        0.0775237 , 0.07057272, 0.07874691, 0.06922147, 0.0742847 ],
       [0.05704067, 0.06618514, 0.06443152, 0.07442536, 0.07024193,
        0.07908645, 0.07212968, 0.07954774, 0.06981503, 0.07464723],
       [0.06117517, 0.0699163 , 0.06755713, 0.07688558, 0.07203949,
        0.08088577, 0.0734313 , 0.08034212, 0.07036819, 0.07499342],
       [0.06637117, 0.07355705, 0.0713011