In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import sys
from copy import copy

sys.path.append('../code/python')
from hat_support import *
from hat_solution import *

### Model without quality

In [2]:
# Parameters
β = 0.92        # Discount Rate
γ = 1.5         # EIS
φ = -0.5        # Borrowing Constraint
σ_ε = 0.25      # Standard deviation of logit shock
N = 2           # Number of countries

# Set up grids
n_p, n_iid, ρ_p, σ_p, σ_iid = 5, 2, 0.9, 0.039**0.5, 0.0522**0.5 
log_zgrid, P = markov_chain(n_p, n_iid, ρ_p, σ_p, σ_iid)
zgrid = np.exp(log_zgrid)
agrid = np.linspace(φ, 8, 100) 

# Country parameters
L = np.array([1, 1])
TFP = np.array([1, 1])
τ = np.array([0, 0])

d_ij = 1.745
d = np.array([[1.0, d_ij], [d_ij, 1.0]])
numeraire_cntry = N-1
ψ_slope = 0.

# Create Model Instance
m = MulticountryHATmodel(β, γ, φ, σ_ε, N, P, L, TFP, τ, d, agrid, zgrid, ψ_slope, numeraire_cntry)

# Solve for the financial globalization equilibrium 
R0 = 1.02
x0 = np.array([R0, 1.0])
eqm = m.find_equilibrium_FG(x0)

In [3]:
# Equilibrium R
eqm.R


1.0141938690670584

In [4]:
# Trade shares
eqm.tradeshares


array([[0.90048373, 0.09951627],
       [0.09951631, 0.90048369]])

In [5]:
# Probability that household 1 buys from country 2
eqm.π_i[:,:,0,1]


array([[0.00747609, 0.0192432 , 0.02024335, 0.03865408, 0.04377192,
        0.06901915, 0.07912538, 0.10381408, 0.12343206, 0.13861941],
       [0.01392841, 0.02121626, 0.0281047 , 0.04282353, 0.05181585,
        0.07116514, 0.08617555, 0.10527656, 0.12709288, 0.13928829],
       [0.01947563, 0.02643934, 0.03571973, 0.04568826, 0.05926711,
        0.07357446, 0.09175838, 0.10661265, 0.12960767, 0.13994122],
       [0.0218411 , 0.02822919, 0.0387705 , 0.04786419, 0.06361865,
        0.0757104 , 0.0957156 , 0.10780557, 0.13105274, 0.14058342],
       [0.02655126, 0.03026675, 0.04297596, 0.05067094, 0.06689129,
        0.07738895, 0.09797106, 0.10891112, 0.13226617, 0.14121594],
       [0.02850408, 0.03330283, 0.04576738, 0.05305944, 0.0701268 ,
        0.07894851, 0.10005029, 0.10996665, 0.13327754, 0.14183652],
       [0.03062496, 0.03522613, 0.04800609, 0.05482747, 0.07194198,
        0.08074442, 0.10178331, 0.11101517, 0.13425263, 0.14244926],
       [0.03339049, 0.03712232, 0.0507749

## Model with quality

In [6]:
# Parameters
β = 0.92        # Discount Rate
γ = 1.5         # EIS
φ = -0.5        # Borrowing Constraint
σ_ε = 0.25      # Standard deviation of logit shock
N = 2           # Number of countries

# Set up grids
n_p, n_iid, ρ_p, σ_p, σ_iid = 5, 2, 0.9, 0.039**0.5, 0.0522**0.5 
log_zgrid, P = markov_chain(n_p, n_iid, ρ_p, σ_p, σ_iid)
zgrid = np.exp(log_zgrid)
agrid = np.linspace(φ, 8, 100) 

# Country parameters
L = np.array([1, 1])
TFP = np.array([1, 1])
τ = np.array([0, 0])

d_ij = 1.745
d = np.array([[1.0, d_ij], [d_ij, 1.0]])
numeraire_cntry = N-1
ψ_slope = 0.2

# Create Model Instance
m_quality = MulticountryHATmodel(β, γ, φ, σ_ε, N, P, L, TFP, τ, d, agrid, zgrid, ψ_slope, numeraire_cntry)

# Solve for the financial globalization equilibrium 
R0 = 1.02
x0 = np.array([R0, 1.0])
eqm_quality = m_quality.find_equilibrium_FG(x0)

In [7]:
# Equilibrium R
eqm_quality.R


1.0126598964524938

In [8]:
# Trade shares
eqm_quality.tradeshares


array([[0.91244779, 0.08755221],
       [0.08755224, 0.91244776]])

In [9]:
# Probability that household 1 buys from country 2
eqm_quality.π_i[:,:,0,1]


array([[0.02039273, 0.03606565, 0.03809814, 0.05054515, 0.05746443,
        0.06403008, 0.07371424, 0.06946104, 0.08332167, 0.06750489],
       [0.03748075, 0.03975362, 0.05245939, 0.05592799, 0.06781308,
        0.06602993, 0.08031119, 0.0704901 , 0.08601554, 0.0678605 ],
       [0.05174034, 0.04896367, 0.06610951, 0.05957307, 0.07733619,
        0.0682849 , 0.08561671, 0.07140896, 0.08791346, 0.06821003],
       [0.05783701, 0.05233146, 0.07152657, 0.06248107, 0.08287319,
        0.07027385, 0.08938908, 0.07223871, 0.08904501, 0.06855331],
       [0.06935247, 0.05607045, 0.07890353, 0.06593821, 0.0870162 ,
        0.07184954, 0.0915636 , 0.07301493, 0.08989438, 0.0688905 ],
       [0.07441266, 0.06128373, 0.08379005, 0.06895098, 0.09112273,
        0.07332221, 0.09353712, 0.07376186, 0.09065479, 0.06922874],
       [0.0797019 , 0.06479619, 0.08781703, 0.0712786 , 0.09345069,
        0.07499828, 0.09518689, 0.07450664, 0.09136561, 0.06955377],
       [0.08625343, 0.0682007 , 0.0925053