In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import sys
from copy import copy


sys.path.append('../code/python')
from hat_support import *
from hat_solution import *

In [2]:
# Parameters
β = 0.92        # Discount Rate
γ = 1.5         # EIS
φ = -0.5        # Borrowing Constraint
σ_ε = 0.25      # Standard deviation of logit shock
N = 2           # Number of countries

# Set up grids
n_p, n_iid, ρ_p, σ_p, σ_iid = 5, 2, 0.9, 0.039**0.5, 0.0522**0.5 
log_zgrid, P = markov_chain(n_p, n_iid, ρ_p, σ_p, σ_iid)
zgrid = np.exp(log_zgrid)
agrid = np.linspace(φ, 8, 100) 

# Country parameters
L = np.array([1, 1])
TFP = np.array([1, 1])
τ = np.array([0, 0])

d_ij = 1.745
d = np.array([[1.0, d_ij], [d_ij, 1.0]])
numeraire_cntry = N-1

# Create Model Instance
m = MulticountryHATmodel(β, γ, φ, σ_ε, N, P, L, TFP, τ, d, agrid, zgrid, numeraire_cntry)


In [3]:
# Solve for the financial globalization equilibrium 

R0 = 1.02
x0 = np.array([R0, 1.0])

eqm = m.find_equilibrium_FG(x0)

In [4]:
# Print trade shares

eqm.tradeshares

array([[0.90048373, 0.09951627],
       [0.09951631, 0.90048369]])

In [5]:
# Find trade elasticities given equilibrium prices

θc, θπ = m.find_trade_elasticities(eqm.R, eqm.w, 0)

In [6]:
θc[:,:,1]

array([[-1.00000002, -0.83103242, -1.00000002, -0.82243401, -1.00000001,
        -0.81411047, -1.        , -0.7400497 , -1.00000001, -0.69476647],
       [-1.00000002, -0.82791842, -1.00000002, -0.82136109, -1.00000002,
        -0.76321098, -1.00000001, -0.72572193, -1.        , -0.69253506],
       [-0.83063416, -0.7651765 , -1.00000002, -0.77135647, -1.00000002,
        -0.75088649, -1.00000001, -0.7169753 , -1.00000001, -0.69041496],
       [-0.82759088, -0.76682707, -0.82239028, -0.77099318, -0.81526682,
        -0.75090473, -1.00000001, -0.71840696, -0.75622318, -0.68875926],
       [-0.76538005, -0.7603205 , -0.82132264, -0.75719083, -0.81454981,
        -0.72928537, -0.79468049, -0.71006781, -0.75847839, -0.68737411],
       [-0.76700886, -0.75842919, -0.77134198, -0.73431725, -0.76351061,
        -0.72520718, -0.79266714, -0.70502774, -0.73773611, -0.68614373],
       [-0.76008893, -0.73928393, -0.75880918, -0.7312257 , -0.76306056,
        -0.72506066, -0.7480799 , -0.70235883

In [7]:
θπ[:,:,1]

array([[-9.98398431, -7.66346142, -7.82123339, -6.11167903, -6.06820523,
        -4.86784684, -4.65061256, -3.81842655, -3.51919116, -3.100121  ],
       [-8.65534924, -7.46560636, -7.08618106, -5.99657768, -5.67151592,
        -4.71380304, -4.4410104 , -3.77113545, -3.41533108, -3.0865158 ],
       [-7.63465491, -6.9006858 , -6.49687117, -5.73264645, -5.32674891,
        -4.63560323, -4.24788471, -3.73585678, -3.32270216, -3.0730803 ],
       [-7.43752664, -6.83408059, -6.12145978, -5.69362628, -4.98935711,
        -4.6053668 , -4.08263379, -3.72725739, -3.25300684, -3.05986112],
       [-6.89062407, -6.65536914, -5.99197789, -5.54672521, -4.91011192,
        -4.51040312, -3.97304643, -3.69103543, -3.24031819, -3.04670356],
       [-6.82644847, -6.56984187, -5.73066465, -5.37010485, -4.73346433,
        -4.45742576, -3.93990884, -3.66249142, -3.20804152, -3.03383354],
       [-6.64470043, -6.3424602 , -5.61408302, -5.29649795, -4.70889656,
        -4.43486243, -3.87296346, -3.63485331