In [409]:
include("ha-endogenous-grid-environment.jl")
include("ha-endogenous-grid-solution.jl")

value_function_fixedpoint (generic function with 2 methods)

In [412]:
R = 1.0291666666666668;
W = 1.00;
Ncntry = 5
Nshocks = 5
Na = 200

prm = model_params(Na = Na, Ncntry = Ncntry, Nshocks = Nshocks)

p = ones(Ncntry, 1);

In [417]:
@time Kgc, Kπprob, v, Q = policy_function_itteration(R, W, p, prm, Niter = 2)

value function may not have converged
check the situation
  3.207874 seconds (24.78 k allocations: 1.869 GiB, 10.72% gc time, 0.36% compilation time)


([0.32465246735834974 0.569782824730923 … 1.0171348352292011 1.0182738317124667; 0.39705615245047704 0.6348565720491556 … 1.017714834593212 1.0182738317124667; … ; 1.0398176574342344 1.1426958591299523 … 2.090984305201505 3.4161464971592377; 1.047257991367216 1.1597491422224606 … 2.1633879902936335 3.488550182251366;;; 0.32465246735834974 0.569782824730923 … 1.0171348352292011 1.0182738317124667; 0.39705615245047704 0.6348565720491556 … 1.017714834593212 1.0182738317124667; … ; 1.0398176574342344 1.1426958591299523 … 2.090984305201505 3.4161464971592377; 1.047257991367216 1.1597491422224606 … 2.1633879902936335 3.488550182251366;;; 0.32465246735834974 0.569782824730923 … 1.0171348352292011 1.0182738317124667; 0.39705615245047704 0.6348565720491556 … 1.017714834593212 1.0182738317124667; … ; 1.0398176574342344 1.1426958591299523 … 2.090984305201505 3.4161464971592377; 1.047257991367216 1.1597491422224606 … 2.1633879902936335 3.488550182251366;;; 0.32465246735834974 0.569782824730923 … 1

In [416]:
v

200×5 Matrix{Float64}:
 -19.1331   -16.5908   -14.7102   -12.9942   -11.1805
 -18.5714   -16.3947   -14.614    -12.9302   -11.1336
 -18.1853   -16.2246   -14.5208   -12.867    -11.087
 -17.8863   -16.0684   -14.4305   -12.8047   -11.0408
 -17.6126   -15.9237   -14.3427   -12.7431   -10.9948
 -17.3854   -15.7899   -14.257    -12.6822   -10.9493
 -17.1755   -15.6621   -14.1734   -12.6221   -10.904
 -16.9861   -15.5401   -14.092    -12.5627   -10.859
 -16.8095   -15.4243   -14.0123   -12.504    -10.8144
 -16.6439   -15.3132   -13.9342   -12.4459   -10.77
 -16.4899   -15.2059   -13.8576   -12.3884   -10.726
 -16.3444   -15.1022   -13.7823   -12.3316   -10.6822
 -16.2059   -15.0019   -13.7083   -12.2753   -10.6388
   ⋮                                         
  -7.50417   -7.18844   -6.77759   -6.2527    -5.69346
  -7.47652   -7.1621    -6.75315   -6.23186   -5.68373
  -7.44897   -7.13587   -6.72884   -6.2112    -5.6745
  -7.42153   -7.10975   -6.70464   -6.19082   -5.66573
  -7.39421   -7.

In [415]:
@time solution, u = value_function_fixedpoint(R, W, p, prm);

solution.zero

  1.339135 seconds (1.21 M allocations: 1.231 GiB, 9.23% gc time, 46.87% compilation time)


200×5 Matrix{Float64}:
 -19.1388   -16.5967   -14.7168   -13.0009   -11.1864
 -18.5771   -16.3988   -14.621    -12.937    -11.1393
 -18.1887   -16.2302   -14.5281   -12.8739   -11.0926
 -17.8985   -16.0734   -14.4385   -12.8113   -11.0462
 -17.6162   -15.9294   -14.3497   -12.7499   -11.0002
 -17.3938   -15.797    -14.2635   -12.6892   -10.9546
 -17.1793   -15.6704   -14.1796   -12.6291   -10.9093
 -16.9929   -15.5459   -14.0986   -12.5694   -10.8643
 -16.8163   -15.431    -14.0194   -12.5105   -10.8196
 -16.6489   -15.3202   -13.9419   -12.4523   -10.7753
 -16.497    -15.2129   -13.8658   -12.3946   -10.7313
 -16.3509   -15.1095   -13.7908   -12.3376   -10.6875
 -16.2141   -15.0088   -13.7166   -12.2813   -10.6441
   ⋮                                         
  -7.50766   -7.19176   -6.78083   -6.25552   -5.69598
  -7.47997   -7.16541   -6.75636   -6.23465   -5.68625
  -7.4524    -7.13916   -6.732     -6.2139    -5.67702
  -7.42494   -7.11303   -6.70775   -6.19357   -5.66825
  -7.3975

In [403]:
foo = [[ones(2,2)]; [ones(2,2)]]

2-element Vector{Matrix{Float64}}:
 [1.0 1.0; 1.0 1.0]
 [1.0 1.0; 1.0 1.0]

In [404]:
foo[2]

2×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0

In [402]:
ones(2,2)

2×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0

In [406]:
bar = Array{Array{Float64}}(undef,2)

2-element Vector{Array{Float64}}:
 #undef
 #undef

In [407]:
bar[1] = ones(2,2)


2×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0

In [408]:
bar = 

2×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0