In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
from support import *
from innovation import *


In [2]:
# Parameters
β = 0.96        # Discount Rate
σ = 3           # EIS
α = 0.36        # Output Elasticity of Capital
δ = 0.08        # Depreciation Rate
φ = -3          # Borrowing Constraint
σ_ε = 0.25      # Standard deviation of logit shock
N = 2           # Number of firms 


### Symmetric Productivities

In [3]:
# Set up grids
log_zgrid, P, estar = tauchen(5, 0.6, 0.3)
zgrid = np.exp(log_zgrid)
agrid = np.linspace(φ, 8, 100) 

# Create Model Instance
m = Aiyagari(β, σ, α, φ, δ, σ_ε, N, P)

# Find equilibrium
z_firm = np.array([1.0, 1.0])
fn = lambda p: m.prices_fp(agrid, zgrid, 1.0, 1.029, z_firm, p)

p0 = np.array([1.0, 1.0])
res = sp.optimize.root(fn, p0)
if res.status == True: print('Model is done!')

p = res.x
ε = m.elasticity(agrid, zgrid, 1.029, 1.0, p)
µ = m.markup(ε)


Model is done!


In [4]:
# Prices
p

array([1.41713173, 1.41713275])

In [5]:
# Elasticities
ε

array([3.48413573, 3.47443511])

In [6]:
# Markups
µ

array([1.40255449, 1.40413264])

### Nonsymmetric Productivities

In [7]:
# Set up grids
log_zgrid, P, estar = tauchen(5, 0.6, 0.3)
zgrid = np.exp(log_zgrid)
agrid = np.linspace(φ, 8, 100) 

# Create Model Instance
m = Aiyagari(β, σ, α, φ, δ, σ_ε, N, P)

# Find equilibrium
z_firm = np.array([0.8, 1.2])
fn = lambda p: m.prices_fp(agrid, zgrid, 1.0, 1.029, z_firm, p)

p0 = np.array([1.0, 1.0])
res = sp.optimize.root(fn, p0)
if res.status == True: print('Model is done!')

p = res.x
ε = m.elasticity(agrid, zgrid, 1.029, 1.0, p)
µ = m.markup(ε)


Model is done!


In [8]:
# Prices
p

array([1.5901999 , 1.47157643])

In [9]:
# Elasticities
ε

array([5.09019995, 2.44528616])

In [10]:
# Markups
µ

array([1.24448682, 1.6919045 ])